### ISSUE TITLE
License Update?

### ISSUE THREAD

**Issue by icosahedron** [darrenstarr/VtNetCore#4]
The readme says that the license is still up in the air, although there is a LICENSE file that has the MIT license included.

Has the license been chosen and approved as MIT?

**Comment by darrenstarr** [comment]
I’m still waiting on feedback from legal, but management is on board. I have 6 sticky notes left on the scrum board for this sprint and that’s one. Whatever license it is, it will be permissive. We don’t believe our project will work under any other license form.

I’ll have an update next week

**Comment by icosahedron** [comment]
Great!  Glad to hear it.  This looks like a very interesting project.

**Comment by migueldeicaza** [comment]
Hello!   We met at Build and we chatted about this, any news on the license?

**Comment by darrenstarr** [comment]
Hey @migueldeicaza my manager(s) are on board, but because of Norway's independence day being celebrated this week, we're struggling to get legal from the parent company on the phone to get the formal corporate policy on open source sorted out.

We're all in agreement with "Whatever license says as long as we can't be sued for someone using or misusing our code, it's all good".

It's a priorirty for me since I'm leaving my current sprint dangling while trying to sort this out.

**Comment by felixse** [comment]
Hey. Sorry for bothering you, but can share any news regarding the license or the future of this project?

**Comment by dgriffen** [comment]
I would also like an update. I'm considering using this in a project but I'm a bit wary if the license isn't technically valid.

**Comment by oising** [comment]
Bump :)

**Comment by brickshot** [comment]
Looks like the license has been clarified as of June 2019. Which is awesome. Thanks @darrenstarr.

**Comment by darrenstarr** [comment]
Yeh... sorry I didn't update it :)
