### ISSUE TITLE
Can't build or use in VS2019

### ISSUE THREAD

**Issue by tig** [darrenstarr/VtNetCore#9]
I spent about 30 min trying to get the dependencies fixed up but had to give up.

I'd really love to give this a deeper look if you have the time to update it to build  under VS2019 (and use dotnetcore3.1 while you're at it <g>).

**Comment by oising** [comment]
What problems are you having? I'm running VS 2019 (latest build) and after a fresh pull of `master`, I did:

![image](https://user-images.githubusercontent.com/1844001/81003457-ed4fa300-8e18-11ea-917a-65d616099177.png)

Used `nuget restore` instead of `dotnet restore` because some of the test projects are using older frameworks AFAICT. Now build:

![image](https://user-images.githubusercontent.com/1844001/81003559-11ab7f80-8e19-11ea-9b3d-94f2b40db8d2.png)

**Comment by oising** [comment]
I'm also running .net core 3.1

**Comment by tig** [comment]
I actually meant to put this issue here: https://github.com/darrenstarr/VtNetCore.UWP

My bad. Closing and opening https://github.com/darrenstarr/VtNetCore.UWP/issues/16
